name: Bug report
description: Report a problem
labels: [bug]
body:
  - type: textarea
    attributes: { label: What happened?, description: Steps to reproduce }
    validations: { required: true }
  - type: textarea
    attributes: { label: Expected behavior }
  - type: textarea
    attributes: { label: Logs/screenshots }
